(()=>{
"use strict";
const NAMES={
1:["Etikk og jegeransvar","Dyrevelferd og respekt","Natur, miljø og forvaltning","Gode valg før jakta","Jegerens rolle i samfunnet"],
2:["Våpendeler og funksjon","Sikker våpenhåndtering","Oppbevaring, transport og utlån","Alder og opplæringsjakt","Ammunisjon, kaliber og anslagsenergi","Rifle og jaktammunisjon","Hagle, plombering og kapasitet","Blyhagl og hagltyper","Våpenkort, tillatelser og ansvar"],
3:["Sikker jaktplanlegging","Trygg skuddretning og bakgrunn","Humane skudd og skuddhold","Samarbeid og kommunikasjon","Vurdering av jaktsituasjonen"],
4:["Hagleskyting og leirduer","Rifleskyting og sikting","Ballistikk og kulebane","Skytestillinger og avtrekk","Trening, kontroll og vedlikehold"],
5:["Hjortevilt","Rovvilt og rovdyr","Småvilt og hare","Hønsefugler","Ender, gjess og sjøfugl","Andre fuglearter","Sel og kystarter","Spor, leveområder og kjennetegn"],
6:["Jakttider og fredning","Jaktkort, avgifter og rapportering","Grunneierrett og jaktrett","Hund, båndtvang og ettersøk","Fangst og lovlige redskaper","Våpen- og ammunisjonsregler","Seljakt og særregler","Alder, ansvar og ledsager"],
7:["Jakt med hund","Stående og støtende fuglehund","Drivende og halsende hund","Løshund og bandhund","Smygjakt, postering og drivjakt","Lokking, lokkefugl og bulvaner","Fangst og feller","Planlegging av jaktformen"],
8:["Skuddtegn og observasjoner","Sporing av skadet vilt","Ettersøkshund og ekvipasje","Plikter og varsling","Sikkerhet under ettersøk"],
9:["Vomming og første behandling","Hygiene og rene arbeidsmåter","Kjøling, transport og lagring","Kjøttkontroll og sykdomstegn","Rapportering og ressursutnyttelse"],
10:["Kart, kompass og GPS","Vær, klær og turutstyr","Førstehjelp og nødssituasjoner","Leir, ild og overnatting","Trygg ferdsel i naturen"]};
const RULES={
1:[["etikk","holdning","respekt","ansvar"],["dyrevelferd","human","lidelse","viltet"],["natur","miljø","forvaltning","bestand","bærekraft"],["plan","før jakta","forberede","avtale"],["samfunn","omdømme","andre mennesker"]],
2:[["løp","sluttstykke","sikring","avtrekker","kolbe","kammer","magasin","våpendel"],["sikker","munning","uladd","kontrollere våpen"],["oppbevar","transport","utlån","våpenskap"],["alder","år","opplæringsjakt","ledsager"],["ammunisjon","kaliber","anslagsenergi","prosjektil","patron"],["rifle","ekspander","kule"],["hagle","plomber","magasin","patroner"],["blyhagl","haglmaterial","stålhagl"],["våpenkort","tillatelse","erverv","politiet"]],
3:[["plan","før jakt","forbered"],["skuddretning","bakgrunn","kulefang","vinkel","rikosjett"],["human","skuddhold","treffområde","avstand"],["radio","kommunikasjon","jaktlag","post"],["situasjon","vurdere","sikker på"]],
4:[["hagle","leirdue","forsving","haglskudd"],["rifle","sikte","innskyting"],["ballistikk","kulebane","anslagsenergi","vind","fall"],["stående","liggende","knestående","avtrekk","anlegg"],["trening","skytebane","vedlikehold","kontroll"]],
5:[["elg","hjort","rådyr","rein"],["bjørn","ulv","gaupe","jerv","rev"],["hare","kanin","småvilt"],["rype","skogsfugl","tiur","røy","orrfugl"],["and","gås","sjøfugl","ærfugl"],["due","kråke","ravn","måke","fugl"],["sel","steinkobbe","havert"],["spor","fot","leveområde","kjennetegn","fjær","pels"]],
6:[["jakttid","fredet","fredning","søndag","jul","påske"],["jegeravgift","jaktkort","rapport","fellingsavgift"],["grunneier","jaktrett","terreng","eiendom"],["hund","båndtvang","ettersøk"],["felle","fangst","redskap"],["våpen","ammunisjon","kaliber","hagle","rifle"],["sel","kvote","kyst"],["alder","ledsager","opplæringsjakt","jegerprøve"]],
7:[["jakthund","hund"],["stående fuglehund","stand","reis"],["drivende","halsende","los"],["løshund","bandhund","elghund"],["smyg","post","drivjakt","støkkjakt"],["lokk","bulvan","lokkefugl","fløyte"],["felle","fangst"],["plan","vind","terreng"]],
8:[["skuddtegn","hår","blod","skuddplass"],["spor","spore","fluktretning"],["ettersøkshund","ekvipasje","hund"],["plikt","varsle","kommune","politi"],["sikker","mørke","våpen"]],
9:[["vom","slakte","utvomming"],["hygiene","ren","forurens"],["kjøl","transport","lagring","temperatur"],["sykdom","kontroll","unormal"],["rapport","ressurs","kjøtt","utnytte"]],
10:[["kart","kompass","gps","kurs","målestokk"],["vær","klær","bekledning","sekk","utstyr"],["førstehjelp","113","skade","blødning","nedkjøling"],["bål","ild","leir","telt","overnatting"],["ferdsel","turplan","nød","sikker"]]};
const lang=()=>typeof profile==="function"?(profile()?.language||"nb"):"nb";
const suffix=(i,l)=>{const all={nb:["grunnlag","i praksis","videre","fordypning","mesteroppdrag"],nn:["grunnlag","i praksis","vidare","fordjuping","meisteroppdrag"],en:["basics","in practice","advanced","deep dive","master mission"]};return(all[l]||all.nb)[Math.min(i,4)]};
function split(list){if(list.length<=25)return[list];const parts=Math.ceil(list.length/25),base=Math.floor(list.length/parts),rest=list.length%parts,out=[];let at=0;for(let i=0;i<parts;i++){const n=base+(i<rest?1:0);out.push(list.slice(at,at+n));at+=n}return out}
function chaptersFor(n){const all=(window.JEGER_QUESTIONS||[]).filter(q=>q.c?.includes(n)),rules=RULES[n]||[],names=NAMES[n]||[],groups=rules.map(()=>[]),other=[];for(const q of all){const text=`${q.q||""} ${q.e||""} ${(q.a||[]).join(" ")}`.toLowerCase();let best=-1,score=0;rules.forEach((words,i)=>{const s=words.reduce((sum,w)=>sum+(text.includes(w)?1:0),0);if(s>score){score=s;best=i}});(best>=0?groups[best]:other).push(q)}const usable=[];groups.forEach((g,i)=>{if(g.length<10)other.push(...g);else usable.push({name:names[i],list:g})});if(other.length)usable.push({name:n===10?"Praktisk turkunnskap":"Blandede situasjoner",list:other});const out=[];for(const g of usable){split(g.list).forEach((list,i)=>out.push({collection:n,name:g.name+(split(g.list).length>1?` – ${suffix(i,lang())}`:""),questions:list}))}return out.map((x,i)=>({...x,index:i+1,code:`${n}.${i+1}`}))}
function count(ch,p){return ch.questions.filter(q=>p.correct?.[q.id]).length}
function completed(ch,p){return count(ch,p)>=Math.min(10,ch.questions.length)}
function allDone(n,p){const cs=chaptersFor(n);return cs.length>0&&cs.every(ch=>completed(ch,p))}
function collectionOpen(n,p){return n===1||allDone(n-1,p)}
function openMap(n){const p=profile(),cs=chaptersFor(n),collection=collections.find(x=>x[0]===n),open=collectionOpen(n,p);if(!open)return;document.getElementById("chapter-map")?.remove();document.body.insertAdjacentHTML("beforeend",`<div class="modal chapter-map" id="chapter-map"><section class="modal-card"><header><div><span class="eyebrow">SAMLING ${n}</span><h2>${collection?.[2]||"🌲"} ${collection?.[1]||"Jegeroppdrag"}</h2><p>Maksimalt 25 spørsmål i hvert deloppdrag. Få 10 forskjellige riktige for å fullføre.</p></div><button id="close-chapters">×</button></header><div class="chapter-grid">${cs.map((ch,i)=>{const prev=i===0||completed(cs[i-1],p),done=completed(ch,p),c=count(ch,p),need=Math.min(10,ch.questions.length);return`<button class="chapter-card ${done?"done":""} ${prev?"":"locked"}" data-chapter="${ch.code}" ${prev?"":"disabled"}><span>${done?"🐾":"🧭"}</span><strong>${ch.code} ${ch.name}</strong><small>${done?"Oppdrag fullført":prev?`${c}/${need} forskjellige riktige`:`🔒 Fullfør ${cs[i-1].code} først`}</small><em>${ch.questions.length} spørsmål</em></button>`}).join("")}</div></section></div>`);document.getElementById("close-chapters").onclick=()=>document.getElementById("chapter-map").remove();document.querySelectorAll("[data-chapter]").forEach(b=>b.onclick=()=>launch(cs.find(x=>x.code===b.dataset.chapter)))}
function launch(ch){if(!ch)return;const p=profile();window.JegerChapters.active=ch.code;sessionStorage.setItem("jeger-active-chapter",ch.code);currentCollection=ch.collection;quiz=orderQuestions(ch.questions,p).slice(0,10).map(q=>window.JegerI18n?.question(q,p.language)||q);document.getElementById("chapter-map")?.remove();startQuiz()}
function smallCelebration(ch,p){p.chapterRewards=p.chapterRewards||{};if(p.chapterRewards[ch.code])return false;p.chapterRewards[ch.code]=Date.now();p.ammo["22"]+=10;p.score+=10;save();document.body.insertAdjacentHTML("beforeend",`<div class="modal hunt-celebration" id="hunt-celebration"><section class="modal-card"><div class="leaf-burst">🍂 🐾 🌿 🐾 🍁</div><img src="jerven-icon.png" alt="Jerven"><span class="eyebrow">OPPDRAG FULLFØRT</span><h2>${ch.code} ${ch.name}</h2><p>Jerven har stemplet oppdraget med et gyllent potespor!</p><strong>+ 10 .22 LR</strong><button id="close-hunt-celebration">Fortsett ›</button></section></div>`);document.getElementById("close-hunt-celebration").onclick=()=>{document.getElementById("hunt-celebration").remove();grandCelebration(ch.collection,p)};return true}
function grandCelebration(n,p){p.collectionRewards=p.collectionRewards||{};if(p.collectionRewards[n]||!allDone(n,p))return;p.collectionRewards[n]=Date.now();p.collectionBadges=p.collectionBadges||[];if(!p.collectionBadges.includes(n))p.collectionBadges.push(n);p.ammo["22"]+=50;p.score+=50;save();const c=collections.find(x=>x[0]===n),adult=p.appearance?.age==="adult",art=adult?(p.avatar==="jente"?"dame-jerven.png":"mann-jerven.png"):(p.avatar==="jente"?"jente-jerven.png":"gutt-jerven.png");document.body.insertAdjacentHTML("beforeend",`<div class="modal grand-celebration" id="grand-celebration"><section class="modal-card"><div class="forest-party">🌲 🐾 🏆 🐾 🌲</div><img src="${art}" alt="Jegeren og Jerven"><span class="eyebrow">HELE SAMLINGEN ER FULLFØRT</span><h2>Samling ${n}: ${c?.[1]||"Jegerprøven"}</h2><p>Du har fullført alle deloppdragene og får et gyllent samlingsmerke!</p><strong>🏅 Samlingsmerke &nbsp; + 50 .22 LR</strong><button id="close-grand">Tilbake til oppdragskartet ›</button></section></div>`);document.getElementById("close-grand").onclick=()=>{document.getElementById("grand-celebration").remove();view="home";render()}}
function check(){const code=sessionStorage.getItem("jeger-active-chapter");if(!code||!document.querySelector(".success"))return;const n=Number(code.split(".")[0]),ch=chaptersFor(n).find(x=>x.code===code),p=profile();if(ch&&completed(ch,p))smallCelebration(ch,p)}
function decorate(){const p=typeof profile==="function"?profile():null;if(!p)return;document.querySelectorAll(".collection[data-col]").forEach(b=>{const n=+b.dataset.col,open=collectionOpen(n,p),cs=chaptersFor(n),done=cs.filter(ch=>completed(ch,p)).length,key=`${open?1:0}:${done}:${cs.length}`;b.disabled=!open;b.classList.toggle("locked",!open);const f=b.querySelector("footer");if(f&&f.dataset.chapterState!==key){f.dataset.chapterState=key;f.innerHTML=open?`🐾 ${done}/${cs.length} deloppdrag <span>›</span>`:`🔒 Fullfør samling ${n-1}`}})}
document.addEventListener("click",e=>{const card=e.target.closest(".collection[data-col]");if(!card)return;e.preventDefault();e.stopImmediatePropagation();openMap(+card.dataset.col)},true);
const style=document.createElement("style");style.textContent=`.chapter-map{z-index:80}.chapter-map .modal-card{width:min(1050px,97vw);height:min(650px,95dvh);display:grid;grid-template-rows:auto minmax(0,1fr);border:5px solid #9a682d;background:linear-gradient(145deg,#fff7d8,#e7c98d);overflow:hidden}.chapter-map header{display:flex;align-items:center}.chapter-map header>div{flex:1}.chapter-map header h2,.chapter-map header p{margin:2px 0}.chapter-map #close-chapters{width:42px;margin:0;padding:5px;font-size:24px}.chapter-grid{min-height:0;overflow:auto;display:grid;grid-template-columns:repeat(3,1fr);gap:9px;padding:7px}.chapter-card{display:grid;grid-template-columns:38px 1fr auto;grid-template-rows:auto auto;align-items:center;text-align:left;border:3px solid #b48442;border-radius:14px;background:linear-gradient(#fff9e6,#ead39d);color:#173d25;padding:10px;box-shadow:0 4px #765020}.chapter-card>span{grid-row:1/3;font-size:27px}.chapter-card strong{font:800 15px Georgia}.chapter-card small{font-size:10px;color:#6e5a35}.chapter-card em{grid-column:3;grid-row:1/3;font-size:9px}.chapter-card.done{background:linear-gradient(#e9f7bd,#9ed659);border-color:#4b9b35}.chapter-card.locked{filter:grayscale(.8);opacity:.55}.hunt-celebration,.grand-celebration{z-index:110}.hunt-celebration .modal-card,.grand-celebration .modal-card{text-align:center;border:6px solid #d39b3d;background:radial-gradient(circle at top,#fff8bd,#e8bd5d);overflow:hidden}.hunt-celebration img{width:120px;border-radius:24px}.leaf-burst,.forest-party{font-size:35px;letter-spacing:10px;animation:huntParty .6s ease-in-out infinite alternate}.hunt-celebration strong,.grand-celebration strong{display:block;padding:12px;border-radius:13px;background:#173d25;color:#fff2c7}.grand-celebration .modal-card{width:min(760px,95vw)}.grand-celebration img{width:230px;max-height:240px;object-fit:contain}.grand-celebration h2{font-size:32px}@keyframes huntParty{from{transform:translateY(-4px) rotate(-1deg)}to{transform:translateY(5px) rotate(1deg)}}@media(orientation:landscape) and (max-height:560px){.chapter-map .modal-card{height:97dvh;padding:7px 11px}.chapter-map header h2{font-size:18px}.chapter-map header p{font-size:9px}.chapter-grid{grid-template-columns:repeat(3,1fr);gap:4px}.chapter-card{padding:5px;grid-template-columns:25px 1fr auto}.chapter-card>span{font-size:18px}.chapter-card strong{font-size:10px}.chapter-card small,.chapter-card em{font-size:7px}.hunt-celebration .modal-card,.grand-celebration .modal-card{padding:8px}.hunt-celebration img{width:65px}.grand-celebration img{width:125px;height:105px}.hunt-celebration h2,.grand-celebration h2{font-size:20px;margin:4px}.hunt-celebration p,.grand-celebration p{font-size:10px;margin:4px}.leaf-burst,.forest-party{font-size:22px}.hunt-celebration strong,.grand-celebration strong{padding:6px}.hunt-celebration button,.grand-celebration button{padding:6px}}`;document.head.appendChild(style);
window.JegerChapters={chaptersFor,openMap,active:null};new MutationObserver(()=>{decorate();check()}).observe(document.getElementById("app"),{childList:true,subtree:true});decorate();
})();
