(()=>{
  "use strict";
  const THEORY_REQUIRED=8, ROUND_MS=30000, FLIGHT_LEAD_MS=125;
  let modal,range,clay,reticle,message,raf,timer,startedAt,nextClayAt,aim={x:400,y:220},target=null,shots=2,hits=0,misses=0,ended=false,last=0;

  function player(){try{return typeof profile==="function"?profile():null}catch{return null}}
  function theoryCount(p){if(!p)return 0;return (window.JEGER_QUESTIONS||window.JEGER_QUESTIONS||[]).filter(q=>q.c?.includes(4)&&p.correct?.[q.id]).length}
  function template(body){return `<div class="clay-modal" id="clay-modal"><section class="clay-card"><header class="clay-head"><h2>🟠 Leirduebanen</h2><span class="clay-stat" id="clay-time">30,0 s</span><span class="clay-stat" id="clay-score">Treff: 0</span><button class="clay-close" id="clay-close">Lukk</button></header>${body}</section></div>`}
  function open(){close();const p=player(),done=theoryCount(p),unlocked=done>=THEORY_REQUIRED;document.body.insertAdjacentHTML("beforeend",template(`<main class="clay-intro"><section class="clay-panel"><h3>${unlocked?"Banen er åpen!":"Fullfør teorien først"}</h3><p>${unlocked?"Før siktet med fingeren eller musen. Kom foran leirdua og fortsett svingen.":`Du har ${done} av ${THEORY_REQUIRED} riktige teorispørsmål i samling 4.`}</p><div class="clay-rules"><span>🦺 Bare sikker skyteretning</span><span>↗️ Sikt foran målet</span><span>🔄 Fortsett svingen</span></div><button class="clay-primary" id="clay-start" ${unlocked?"":"disabled"}>Start 30 sekunder</button>${unlocked?"":`<button class="clay-primary" id="clay-theory">Øv på teorien</button>`}</section></main>`));modal=document.getElementById("clay-modal");bindClose();document.getElementById("clay-start")?.addEventListener("click",start);document.getElementById("clay-theory")?.addEventListener("click",()=>{close();if(typeof startCollection==="function")startCollection(4)})}
  function bindClose(){document.getElementById("clay-close")?.addEventListener("click",close)}
  function start(){modal.innerHTML=`<section class="clay-card"><header class="clay-head"><h2>🟠 Leirduebanen</h2><span class="clay-stat" id="clay-time">30,0 s</span><span class="clay-stat" id="clay-score">Treff: 0</span><button class="clay-close" id="clay-close">Avslutt</button></header><main class="clay-range" id="clay-range" aria-label="Virtuell leirduebane"><div class="clay-reticle" id="clay-reticle"></div><div class="clay-message" id="clay-message"></div><div class="clay-controls"><div class="clay-shells" id="clay-shells"></div><div class="clay-buttons"><button class="clay-reload" id="clay-reload">↻ LAD</button><button class="clay-fire" id="clay-fire">SKYT</button></div></div></main></section>`;bindClose();range=document.getElementById("clay-range");reticle=document.getElementById("clay-reticle");message=document.getElementById("clay-message");hits=misses=0;shots=2;ended=false;startedAt=performance.now();last=startedAt;nextClayAt=startedAt+350;target=null;moveAim(range.clientWidth*.52,range.clientHeight*.45);range.addEventListener("pointermove",pointer);range.addEventListener("pointerdown",pointer);document.getElementById("clay-fire").addEventListener("click",fire);document.getElementById("clay-reload").addEventListener("click",reload);window.addEventListener("keydown",key);drawShells();raf=requestAnimationFrame(loop)}
  function pointer(e){const r=range.getBoundingClientRect();moveAim(e.clientX-r.left,e.clientY-r.top)}
  function moveAim(x,y){if(!range)return;aim.x=Math.max(25,Math.min(range.clientWidth-25,x));aim.y=Math.max(25,Math.min(range.clientHeight*.70,y));reticle.style.left=aim.x+"px";reticle.style.top=aim.y+"px"}
  function key(e){if(e.code==="Space"){e.preventDefault();fire()}if(e.key.toLowerCase()==="r")reload()}
  function spawn(now){if(clay)clay.remove();clay=document.createElement("div");clay.className="clay";range.appendChild(clay);const right=Math.random()>.5,speed=190+Math.random()*115,startY=range.clientHeight*(.55+Math.random()*.08);target={x:right?-30:range.clientWidth+30,y:startY,vx:right?speed:-speed,vy:-(155+Math.random()*80),gravity:150,angle:right?8:-8};nextClayAt=Infinity;placeClay()}
  function placeClay(){if(!clay||!target)return;clay.style.left=(target.x-21)+"px";clay.style.top=(target.y-8)+"px";clay.style.transform=`rotate(${target.angle}deg)`}
  function loop(now){if(ended)return;const dt=Math.min(.04,(now-last)/1000);last=now;const left=Math.max(0,ROUND_MS-(now-startedAt));document.getElementById("clay-time").textContent=(left/1000).toFixed(1).replace(".",",")+" s";if(left<=0)return finish();if(!target&&now>=nextClayAt)spawn(now);if(target){target.vy+=target.gravity*dt;target.x+=target.vx*dt;target.y+=target.vy*dt;placeClay();if(target.x<-80||target.x>range.clientWidth+80||target.y<-60||target.y>range.clientHeight*.72){misses++;removeTarget();feedback("Følg bevegelsen og kom foran")}}raf=requestAnimationFrame(loop)}
  function fire(){if(ended)return;if(shots<=0)return feedback("Du må lade");shots--;drawShells();if(!target)return feedback("Vent til leirdua er kastet");const lead=FLIGHT_LEAD_MS/1000,predX=target.x+target.vx*lead,predY=target.y+target.vy*lead+.5*target.gravity*lead*lead,d=Math.hypot(aim.x-predX,aim.y-predY);if(d<48){hits++;document.getElementById("clay-score").textContent=`Treff: ${hits}`;clay.classList.add("hit");target=null;setTimeout(()=>{clay?.remove();clay=null},260);nextClayAt=performance.now()+420;feedback("TREFF! Fortsett svingen 👏")}else{misses++;const along=(aim.x-target.x)*Math.sign(target.vx);feedback(along<5?"Du lå litt bak":"Nesten – hold en jevn sving")}}
  function reload(){if(ended||shots===2)return;const b=document.getElementById("clay-reload");b.disabled=true;b.textContent="Lader …";setTimeout(()=>{if(ended)return;shots=2;drawShells();b.disabled=false;b.textContent="↻ LAD"},700)}
  function drawShells(){const box=document.getElementById("clay-shells");if(box)box.innerHTML=[0,1].map(i=>`<i class="clay-shell ${i<shots?"":"empty"}"></i>`).join("")}
  function removeTarget(){clay?.remove();clay=null;target=null;nextClayAt=performance.now()+500}
  function feedback(text){message.textContent=text;message.classList.add("show");clearTimeout(timer);timer=setTimeout(()=>message?.classList.remove("show"),850)}
  function finish(){ended=true;cancelAnimationFrame(raf);window.removeEventListener("keydown",key);const p=player(),reward=Math.floor(hits/3);if(p&&reward){p.ammo=p.ammo||{22:0,12:0,65:0};p.ammo[22]=(p.ammo[22]||0)+reward;p.score=(p.score||0)+reward;p.clayBest=Math.max(p.clayBest||0,hits);if(typeof save==="function")save()}modal.innerHTML=`<section class="clay-card"><header class="clay-head"><h2>🟠 Leirduebanen</h2><button class="clay-close" id="clay-close">Lukk</button></header><main class="clay-result"><section class="clay-panel"><h3>${hits>=8?"Strålende skyting!":"God trening!"}</h3><p><strong>${hits} treff</strong> på 30 sekunder.</p><p>${reward?`Du tjente ${reward} .22 LR-patron${reward===1?"":"er"}.`:"Tre treff gir én .22 LR-patron. Prøv igjen!"}</p><button class="clay-primary" id="clay-again">Prøv igjen</button></section></main></section>`;bindClose();document.getElementById("clay-again").addEventListener("click",start)}
  function close(){ended=true;cancelAnimationFrame(raf);clearTimeout(timer);window.removeEventListener("keydown",key);document.getElementById("clay-modal")?.remove();modal=range=clay=reticle=message=null}
  window.ClayRange={open,close,theoryRequired:THEORY_REQUIRED};
})();
