(()=>{
"use strict";
const CONFIG={apiKey:"AIzaSyAtU4onVfwOvJurOeedzdlarlAGCpBFeww",authDomain:"jegerproven-multiplayer.firebaseapp.com",databaseURL:"https://jegerproven-multiplayer-default-rtdb.europe-west1.firebasedatabase.app",projectId:"jegerproven-multiplayer",storageBucket:"jegerproven-multiplayer.firebasestorage.app",messagingSenderId:"189672059510",appId:"1:189672059510:web:36b3229ec6b1d0ad46e557"};
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lang=()=>typeof profile==="function"?(profile()?.language||"nb"):"nb";
const TX={nb:{title:"Global resultatliste",card:"Global scoreboard",desc:"Se alle jegere som har spilt.",open:"Åpne",points:"Patronpoeng",correct:"Riktige",streak:"Beste rekke",player:"Jeger",close:"Lukk",loading:"Henter resultatlisten …",offline:"Kunne ikke hente listen nå. Prøv igjen når du er tilkoblet.",privacy:"Spillerne vises med anonyme jegernavn."},nn:{title:"Global resultatliste",card:"Global scoreboard",desc:"Sjå alle jegerar som har spelt.",open:"Opna",points:"Patronpoeng",correct:"Rette",streak:"Beste rekkje",player:"Jeger",close:"Lukk",loading:"Hentar resultatlista …",offline:"Klarte ikkje henta lista no. Prøv igjen når du er tilkopla.",privacy:"Spelarane blir viste med anonyme jegernamn."},en:{title:"Global leaderboard",card:"Global leaderboard",desc:"See every hunter who has played.",open:"Open",points:"Ammo points",correct:"Correct",streak:"Best streak",player:"Hunter",close:"Close",loading:"Loading the leaderboard …",offline:"Could not load the leaderboard. Try again when connected.",privacy:"Players are shown with anonymous hunter names."}};
const text=()=>TX[lang()]||TX.nb;
let app,auth,rtdb,uid;
async function init(){if(!globalThis.firebase)throw Error("Firebase er ikke tilgjengelig.");app=firebase.apps.length?firebase.app():firebase.initializeApp(CONFIG);auth=firebase.auth();rtdb=firebase.database(app);uid=auth.currentUser?.uid||(await auth.signInAnonymously()).user.uid}
function alias(p){const clean=String(p?.id||"0000").replace(/[^a-z0-9]/gi,"").toUpperCase();return`Jeger ${clean.slice(-4).padStart(4,"0")}`}
function payload(p){return{alias:alias(p),score:Number(p?.score||0),correct:Object.values(p?.correct||{}).filter(Boolean).length,bestStreak:Number(p?.bestStreak||0),ownerUid:uid,updatedAt:firebase.database.ServerValue.TIMESTAMP}}
async function sync(){const p=typeof profile==="function"?profile():null;if(!p||!navigator.onLine)return;try{await init();await rtdb.ref(`globalScoreboard/${p.id}`).update(payload(p))}catch{}}
function addCard(){const tools=document.querySelector(".game-tools");if(!tools||document.getElementById("global-scoreboard"))return;const t=text();tools.insertAdjacentHTML("beforeend",`<section class="score-card global-score-card"><i>🌍</i><div><h3>${esc(t.card)}</h3><p>${esc(t.desc)}</p></div><button class="install" id="global-scoreboard">${esc(t.open)}</button></section>`);document.getElementById("global-scoreboard").onclick=open;sync()}
function renderRows(data,myId){const t=text(),rows=Object.entries(data||{}).map(([id,x])=>({id,...x})).sort((a,b)=>(b.score||0)-(a.score||0)||(b.correct||0)-(a.correct||0)||(b.bestStreak||0)-(a.bestStreak||0)).slice(0,100);if(!rows.length)return`<p>${esc(t.offline)}</p>`;return`<div class="leader-head"><b>#</b><b>${esc(t.player)}</b><b>${esc(t.points)}</b><b>${esc(t.correct)}</b><b>${esc(t.streak)}</b></div><ol class="leader-list">${rows.map((x,i)=>`<li class="${x.id===myId?"mine":""}"><b>${i+1}</b><strong>${esc(x.alias||"Jeger")}${x.id===myId?" ⭐":""}</strong><span>${Number(x.score||0)}</span><span>${Number(x.correct||0)}</span><span>${Number(x.bestStreak||0)}</span></li>`).join("")}</ol>`}
async function open(){const p=typeof profile==="function"?profile():null,t=text();document.getElementById("leaderboard-modal")?.remove();document.body.insertAdjacentHTML("beforeend",`<div class="modal leaderboard-modal" id="leaderboard-modal"><section class="modal-card"><header><div><span class="eyebrow">🌍 ALLE SPILLERE</span><h2>${esc(t.title)}</h2></div><button id="close-leaderboard">×</button></header><small>🔒 ${esc(t.privacy)}</small><div class="leader-content" id="leader-content"><p>${esc(t.loading)}</p></div><button id="leader-done">${esc(t.close)}</button></section></div>`);const close=()=>document.getElementById("leaderboard-modal")?.remove();document.getElementById("close-leaderboard").onclick=close;document.getElementById("leader-done").onclick=close;try{await init();await rtdb.ref(`globalScoreboard/${p.id}`).update(payload(p));const snap=await rtdb.ref("globalScoreboard").orderByChild("score").limitToLast(100).once("value");document.getElementById("leader-content").innerHTML=renderRows(snap.val(),p.id)}catch{document.getElementById("leader-content").innerHTML=`<p>${esc(t.offline)}</p>`}}
const style=document.createElement("style");style.textContent=`.leaderboard-modal{z-index:96}.leaderboard-modal .modal-card{width:min(760px,96vw);height:min(620px,94dvh);display:grid;grid-template-rows:auto auto minmax(0,1fr) auto;border:5px solid #9a682d;background:linear-gradient(145deg,#fff7d8,#e7c98d);overflow:hidden}.leaderboard-modal header{display:flex;align-items:center}.leaderboard-modal header>div{flex:1}.leaderboard-modal header h2{margin:3px 0}.leaderboard-modal #close-leaderboard{width:42px;margin:0;padding:5px;font-size:24px}.leader-content{min-height:0;overflow:auto;margin-top:8px;border:3px solid #b48b4b;border-radius:13px;background:#fff8e6}.leader-head,.leader-list li{display:grid;grid-template-columns:42px minmax(120px,1fr) repeat(3,90px);gap:5px;align-items:center;padding:8px 10px}.leader-head{position:sticky;top:0;z-index:2;background:#173d25;color:#fff1c8;font-size:11px}.leader-list{list-style:none;margin:0;padding:0}.leader-list li{border-bottom:1px solid #d8bd83;color:#173d25}.leader-list li.mine{background:#dff1bd;border:3px solid #61a43c;border-radius:9px}.leader-list span{text-align:center;font-weight:800}.leaderboard-modal #leader-done{margin-top:8px}@media(orientation:landscape) and (max-height:560px){.leaderboard-modal .modal-card{height:97dvh;padding:7px 11px}.leaderboard-modal header h2{font-size:18px}.leader-head,.leader-list li{grid-template-columns:28px minmax(100px,1fr) repeat(3,65px);padding:4px 7px;font-size:9px}.leaderboard-modal #leader-done{padding:5px;margin-top:4px}}`;document.head.appendChild(style);
new MutationObserver(addCard).observe(document.getElementById("app"),{childList:true,subtree:true});window.addEventListener("online",sync);addCard();
})();
