(()=>{
"use strict";
const T=[
{nb:["anslagsenergi","Hvor mye bevegelsesenergi prosjektilet har når det treffer. Fart påvirker energien svært mye, men vekten på prosjektilet betyr også noe."],nn:["anslagsenergi","Kor mykje rørsleenergi prosjektilet har når det treffer. Farten påverkar energien svært mykje, men vekta på prosjektilet betyr òg noko."],en:["impact energy","The projectile's kinetic energy when it hits. Speed has a major effect, and projectile mass also matters."]},
{nb:["prosjektil","Den delen av patronen som forlater løpet og går mot målet. I en riflepatron er dette kula."],nn:["prosjektil","Den delen av patrona som forlèt løpet og går mot målet. I ei riflepatron er dette kula."],en:["projectile","The part of a cartridge that leaves the barrel and travels towards the target. In a rifle cartridge, this is the bullet."]},
{nb:["bevegelsesenergi","Energi noe har fordi det beveger seg. Høyere fart eller større masse gir mer bevegelsesenergi."],nn:["rørsleenergi","Energi noko har fordi det rører seg. Høgare fart eller større masse gir meir rørsleenergi."],en:["kinetic energy","Energy an object has because it is moving. Greater speed or mass gives more kinetic energy."]},
{nb:["treffpunkt","Det nøyaktige stedet der haglene eller prosjektilet treffer."],nn:["treffpunkt","Den nøyaktige staden der hagla eller prosjektilet treffer."],en:["point of impact","The exact place where the shot pellets or projectile hit."]},
{nb:["tilstrekkelig virkning","At riktig ammunisjon, ved et godt plassert skudd, har nok energi og egnet konstruksjon til å avlive det aktuelle viltet raskt og humant."],nn:["tilstrekkeleg verknad","At rett ammunisjon, ved eit godt plassert skot, har nok energi og eigna konstruksjon til å avliva viltet raskt og humant."],en:["sufficient effect","The correct ammunition has enough energy and suitable construction, with a well-placed shot, to kill the game quickly and humanely."]},
{nb:["treningsammunisjon","Skarp ammunisjon laget først og fremst for trening, blinkskyting eller konkurranse. Den kan være dødelig, men prosjektilet er ikke nødvendigvis konstruert eller godkjent som jaktammunisjon."],nn:["treningsammunisjon","Skarp ammunisjon laga først og fremst for trening, blinkskyting eller konkurranse. Han kan vera dødeleg, men prosjektilet er ikkje nødvendigvis laga eller godkjent som jaktammunisjon."],en:["training ammunition","Live ammunition mainly made for practice, target shooting or competition. It can be lethal, but the projectile may not be designed or approved for hunting."]},
{nb:["stand","Når en stående fuglehund stanser og markerer med kropp og hode hvor den kjenner lukt av fugl."],nn:["stand","Når ein ståande fuglehund stansar og markerer med kropp og hovud kvar han kjenner lukt av fugl."],en:["point","When a pointing dog stops and uses its body and head to indicate where it scents a bird."]},
{nb:["stående fuglehund","En hund som søker etter fugl og tar stand når den finner den. Jegeren går rolig fram før fuglen eventuelt reises."],nn:["ståande fuglehund","Ein hund som søkjer etter fugl og tek stand når han finn fuglen. Jegeren går roleg fram før fuglen eventuelt blir reist."],en:["pointing dog","A dog that searches for birds and points when it finds one. The hunter moves forward calmly before the bird may be flushed."]},
{nb:["skuddvinkel","Retningen skuddet går i – oppover, vannrett eller nedover – og hva som finnes foran, bak og under målet."],nn:["skotvinkel","Retninga skotet går i – oppover, vassrett eller nedover – og kva som finst framfor, bak og under målet."],en:["shot angle","The direction of the shot — upward, level or downward — and what is in front of, behind and below the target."]},
{nb:["kulefang","Trygg bakgrunn som kan stanse prosjektilet, for eksempel egnet jordvoll eller fast mark uten fare for rikosjett."],nn:["kulefang","Trygg bakgrunn som kan stansa prosjektilet, til dømes ein eigna jordvoll eller fast mark utan fare for rikosjett."],en:["backstop","A safe background that can stop the projectile, such as a suitable earth bank or solid ground without ricochet danger."]},
{nb:["rikosjett","Når et prosjektil eller hagl slår mot en hard flate og endrer retning."],nn:["rikosjett","Når eit prosjektil eller hagl slår mot ei hard flate og endrar retning."],en:["ricochet","When a projectile or pellet strikes a hard surface and changes direction."]},
{nb:["våtmark","Et bredt begrep som blant annet kan omfatte vann, myr og områder som er vannmettet hele eller deler av året."],nn:["våtmark","Eit breitt omgrep som mellom anna kan omfatta vatn, myr og område som er vassmetta heile eller delar av året."],en:["wetland","A broad term that can include water, marshes and land that is waterlogged throughout or during part of the year."]},
{nb:["plombert","Fysisk begrenset slik at et magasin ikke kan romme flere patroner enn regelen tillater. Det er ikke nok bare å la være å fylle magasinet."],nn:["plombert","Fysisk avgrensa slik at eit magasin ikkje kan romma fleire patroner enn regelen tillèt. Det er ikkje nok berre å la vera å fylla magasinet."],en:["permanently restricted","Physically restricted so a magazine cannot hold more cartridges than permitted. Simply choosing not to fill it is not enough."]},
{nb:["los","Lyden hunden gir mens den arbeider med vilt. Lyden kan hjelpe jegeren å forstå hvor hund og vilt befinner seg."],nn:["los","Lyden hunden gir medan han arbeider med vilt. Lyden kan hjelpa jegeren å forstå kvar hunden og viltet er."],en:["giving tongue","The sound a dog makes while working game. It can help the hunter understand where the dog and game are."]},
{nb:["gir hals","At hunden bruker stemmen og bjeffer eller loser under arbeidet."],nn:["gir hals","At hunden brukar røysta og bjeffar eller losar under arbeidet."],en:["gives tongue","The dog uses its voice, barking or giving tongue while working."]},
{nb:["apport","At hunden finner og bringer felt eller skadet småvilt tilbake til føreren."],nn:["apport","At hunden finn og bringar felt eller skadd småvilt tilbake til føraren."],en:["retrieve","The dog finds and brings harvested or wounded small game back to its handler."]}
];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const lang=()=>typeof profile==="function"?(profile()?.language||"nb"):"nb";
function onScreen(){const box=document.querySelector(".question");if(!box)return[];const l=lang(),text=box.innerText.toLowerCase();return T.map(x=>x[l]).filter(([term])=>text.includes(term.toLowerCase()))}
function guide(text,l){const s=text.trim().toLowerCase(),kind=s.startsWith("hvorfor")?"why":s.startsWith("når")?"when":s.startsWith("hvor mange")||s.includes("aldersgrense")?"number":s.startsWith("hva betyr")||s.startsWith("hva beskriver")?"meaning":s.startsWith("kan ")||s.includes("lov å")?"rule":s.startsWith("hvordan")||s.startsWith("hva gjør")?"action":"choose",tips={nb:{why:"Her skal du finne årsaken. Se etter alternativet som forklarer hvorfor regelen eller handlingen er viktig.",when:"Her skal du finne riktig tidspunkt eller vilkår. Legg merke til ord som beskriver når regelen gjelder.",number:"Her spørres det etter en bestemt grense, alder eller et antall. Skill mellom kalenderåret og selve bursdagen dersom alder er nevnt.",meaning:"Her skal du kjenne igjen betydningen av et faguttrykk. Velg forklaringen som passer til hvordan ordet brukes i jakt.",rule:"Her skal du vurdere hva regelverket tillater. Les hele spørsmålet og se etter begrensninger eller vilkår.",action:"Her spørres det etter riktig framgangsmåte. Tenk sikkerhet, dyrevelferd og hva jegeren skal gjøre først.",choose:"Finn nøkkelordet i spørsmålet. Sammenlign deretter alle tre svarene og velg det som passer best til akkurat situasjonen."},nn:{why:"Her skal du finna årsaka. Sjå etter alternativet som forklarer kvifor regelen eller handlinga er viktig.",when:"Her skal du finna rett tidspunkt eller vilkår. Legg merke til ord som skildrar når regelen gjeld.",number:"Her blir det spurt etter ei bestemt grense, ein alder eller eit tal. Skil mellom kalenderåret og sjølve fødselsdagen dersom alder er nemnd.",meaning:"Her skal du kjenna att tydinga av eit faguttrykk. Vel forklaringa som passar til korleis ordet blir brukt i jakt.",rule:"Her skal du vurdera kva regelverket tillèt. Les heile spørsmålet og sjå etter avgrensingar eller vilkår.",action:"Her blir det spurt etter rett framgangsmåte. Tenk tryggleik, dyrevelferd og kva jegeren skal gjera først.",choose:"Finn nøkkelordet i spørsmålet. Samanlikn så alle tre svara og vel det som passar best til akkurat situasjonen."},en:{why:"Find the reason. Look for the option that explains why the rule or action matters.",when:"Find the correct time or condition. Notice words that describe when the rule applies.",number:"Look for a specific limit, age or number. If age is mentioned, distinguish the calendar year from the actual birthday.",meaning:"Recognise the meaning of a technical term. Choose the explanation that matches how the word is used in hunting.",rule:"Decide what the rules permit. Read the whole question and look for limitations or conditions.",action:"Choose the correct procedure. Think about safety, animal welfare and what the hunter should do first.",choose:"Find the key words in the question. Compare all three options and choose the one that best fits this exact situation."}};return tips[l]?.[kind]||tips.nb[kind]}
function add(){const q=document.querySelector(".question"),heading=q?.querySelector("h1");if(!q||!heading||q.querySelector(".word-help"))return;const terms=onScreen(),l=lang(),question=heading.textContent.trim(),label=l==="en"?"❓ Help with this question":l==="nn"?"❓ Hjelp til spørsmålet":"❓ Hjelp til spørsmålet",b=document.createElement("button");b.type="button";b.className="word-help";b.textContent=label;b.onclick=()=>open(question,terms,l);heading.insertAdjacentElement("afterend",b)}
function open(question,terms,l){document.getElementById("word-help-modal")?.remove();const title=l==="en"?"Help with this question":l==="nn"?"Hjelp til dette spørsmålet":"Hjelp til dette spørsmålet",intro=l==="en"?"The help is made for the question on screen. It explains what to look for without revealing the answer.":l==="nn"?"Hjelpa er laga for spørsmålet på skjermen. Ho forklarer kva du skal sjå etter utan å røpa svaret.":"Hjelpen er laget for spørsmålet på skjermen. Den forklarer hva du skal se etter uten å røpe svaret.",words=l==="en"?"Words used in the task":l==="nn"?"Ord som er brukte i oppgåva":"Ord som brukes i oppgaven",close=l==="en"?"I understand ›":l==="nn"?"Eg forstår ›":"Jeg forstår ›",eye=l==="en"?"HELP WITHOUT REVEALING THE ANSWER":l==="nn"?"HJELP UTAN Å RØPA SVARET":"HJELP UTEN Å RØPE SVARET";document.body.insertAdjacentHTML("beforeend",`<div class="modal word-help-modal" id="word-help-modal"><section class="modal-card"><span class="eyebrow">${eye}</span><h2>${title}</h2><blockquote>${esc(question)}</blockquote><p>${esc(intro)}</p><div class="question-guide">${esc(guide(question,l))}</div>${terms.length?`<h3>${words}</h3><div class="word-list">${terms.map(([t,d])=>`<article><strong>${esc(t)}</strong><span>${esc(d)}</span></article>`).join("")}</div>`:""}<button id="close-word-help">${close}</button></section></div>`);document.getElementById("close-word-help").onclick=()=>document.getElementById("word-help-modal")?.remove()}
const style=document.createElement("style");style.textContent=`.word-help{display:inline-flex;align-items:center;gap:6px;margin:-2px 0 8px;border:2px solid #b58942;border-radius:11px;background:#fff1bf;color:#493615;padding:7px 11px;font-weight:900;box-shadow:0 2px #8e6a32}.word-help-modal .modal-card{width:min(700px,94vw);border:5px solid #9a682d;background:linear-gradient(145deg,#fff7d8,#e7c98d)}.word-help-modal h2{margin:5px 0}.word-help-modal blockquote{margin:7px 0;padding:8px 12px;border-left:5px solid #b7832e;background:#fff9e8;color:#173d25;font:700 18px/1.3 Georgia}.question-guide{margin:8px 0;padding:11px;border:2px solid #709061;border-radius:12px;background:#e5f0d8;color:#173d25;font-weight:800;line-height:1.4}.word-help-modal h3{margin:9px 0 5px;font:800 18px Georgia}.word-list{display:grid;gap:7px;max-height:34vh;overflow:auto}.word-list article{display:grid;grid-template-columns:minmax(110px,28%) 1fr;gap:10px;background:#fff9e8;border:2px solid #c9a45d;border-radius:11px;padding:9px;color:#173d25}.word-list strong{text-transform:capitalize}.word-list span{line-height:1.35}@media(orientation:landscape) and (max-height:560px){.word-help{padding:3px 7px;font-size:9px;margin:0 0 3px}.word-help-modal .modal-card{padding:8px 11px}.word-help-modal h2{font-size:18px}.word-help-modal blockquote{font-size:12px;margin:3px 0;padding:4px 8px}.word-help-modal p,.question-guide,.word-list article{font-size:9px;margin:3px 0;padding:5px}.word-help-modal h3{font-size:12px;margin:3px}.word-list{max-height:26vh}}`;document.head.appendChild(style);new MutationObserver(add).observe(document.getElementById("app"),{childList:true,subtree:true});add();
})();
