(() => {
  "use strict";
  const CONFIG={
    apiKey:"AIzaSyAtU4onVfwOvJurOeedzdlarlAGCpBFeww",
    authDomain:"jegerproven-multiplayer.firebaseapp.com",
    databaseURL:"https://jegerproven-multiplayer-default-rtdb.europe-west1.firebasedatabase.app",
    projectId:"jegerproven-multiplayer",
    storageBucket:"jegerproven-multiplayer.firebasestorage.app",
    messagingSenderId:"189672059510",
    appId:"1:189672059510:web:36b3229ec6b1d0ad46e557",
    measurementId:"G-085R81TGSE"
  };
  const ROUND_MS=30000,MAX_PLAYERS=12,COUNTDOWN_MS=3500,ROOM_LIFETIME=2*60*60*1000,SESSION_KEY="jegerproven-mp-room";
  let app,auth,rtdb,uid,roomCode,roomRef,roomData,unsubscribe,offset=0,timer,questionIndex=0,correct=0,wrong=0,totalResponseMs=0,questionShownAt=0,finished=false,currentAttempts=0,earnedPoints=0,statsSaved=false;
  const $=s=>document.querySelector(s),safe=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));
  const me=()=>typeof profile==="function"?profile():{name:"Spiller",avatar:"gutt",dog:"Jerven"};
  const now=()=>Date.now()+offset;
  const codeFromUrl=()=>new URLSearchParams(location.search).get("challenge")?.toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6)||"";
  function screen(html){document.getElementById("mp-root")?.remove();document.body.insertAdjacentHTML("beforeend",`<main class="mp-screen" id="mp-root"><div class="mp-net ${navigator.onLine?"online":"offline"}" id="mp-net">${navigator.onLine?"● Tilkoblet":"● Uten nett"}</div>${html}</main>`)}
  function panel(body,close=true){return`<section class="mp-panel"><header class="mp-title"><img src="jerven-icon.png" alt="Jerven"><div><h1>Vennekamp</h1><p>Flest riktige på 30 sekunder</p></div>${close?'<button class="mp-btn secondary mp-close" data-mp-close>✕ Lukk</button>':""}</header>${body}</section>`}
  function error(message){const old=$(".mp-error");if(old)old.remove();$(".mp-panel")?.insertAdjacentHTML("beforeend",`<p class="mp-error">${safe(message)}</p>`)}
  async function init(){
    if(uid)return;
    if(!globalThis.firebase)throw new Error("Kunne ikke koble til spillserveren. Kontroller internettforbindelsen.");
    app=firebase.apps.length?firebase.app():firebase.initializeApp(CONFIG);auth=firebase.auth();rtdb=firebase.database();
    const cred=auth.currentUser?{user:auth.currentUser}:await auth.signInAnonymously();uid=cred.user.uid;
    rtdb.ref(".info/serverTimeOffset").on("value",s=>offset=s.val()||0);
    rtdb.ref(".info/connected").on("value",s=>{setNet(Boolean(s.val()));if(s.val()&&roomRef&&roomCode)markConnected()});
  }
  async function open(){
    const remembered=codeFromUrl()||localStorage.getItem(SESSION_KEY)||"";screen(panel(`<div class="mp-actions"><article class="mp-card"><h2>🏕️ Lag spillerom</h2><p>Du blir vert. Velg spørsmålene før rommet lages.</p><label>Samling<select class="mp-select" id="mp-category"><option value="0">Alle samlinger</option>${[1,2,3,4,5,6,7,8,9,10].map(n=>`<option value="${n}">Samling ${n}</option>`).join("")}</select></label><label>Vanskelighet<select class="mp-select" id="mp-difficulty"><option value="all">Blandet</option><option value="22">Lett</option><option value="12">Middels</option><option value="65">Vanskelig</option></select></label><button class="mp-btn" id="mp-create">Lag nytt rom</button></article><article class="mp-card"><h2>📱 Bli med</h2><p>Skriv romkoden som vises på telefonen til verten.</p><input class="mp-input" id="mp-code" maxlength="6" inputmode="text" placeholder="ABC123" value="${safe(remembered)}"><button class="mp-btn" id="mp-join">${remembered?"Koble til igjen":"Bli med"}</button><button class="mp-btn secondary" id="mp-test">Test tilkoblingen</button></article></div>`));bindClose();
    try{await init()}catch(e){error(e.message);return}
    $("#mp-create").onclick=createRoom;$("#mp-join").onclick=()=>joinRoom($("#mp-code").value);$("#mp-test").onclick=selfTest;if(codeFromUrl())$("#mp-join").focus();
  }
  function bindClose(){$("[data-mp-close]")?.addEventListener("click",leave)}
  function setNet(connected){const n=$("#mp-net");if(!n)return;n.className=`mp-net ${connected?"online":"offline"}`;n.textContent=connected?"● Tilkoblet":"● Uten nett – prøver igjen"}
  async function markConnected(){if(!roomRef||!uid)return;const mine=roomRef.child(`players/${uid}`);await mine.update({connected:true,lastSeen:firebase.database.ServerValue.TIMESTAMP});mine.onDisconnect().update({connected:false,lastSeen:firebase.database.ServerValue.TIMESTAMP})}
  async function selfTest(){const b=$("#mp-test");b.disabled=true;b.textContent="Tester …";try{await init();const snap=await rtdb.ref(".info/connected").once("value");if(!snap.val())throw new Error("Ingen forbindelse til Firebase");if(!(window.JEGER_QUESTIONS||[]).length)throw new Error("Spørsmålene mangler");b.textContent=`✓ Alt virker (${window.JEGER_QUESTIONS.length} spørsmål)`}catch(e){b.disabled=false;b.textContent="Prøv igjen";error("Tilkoblingstesten feilet: "+e.message)}}
  function makeCode(){const chars="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";return Array.from({length:6},()=>chars[Math.floor(Math.random()*chars.length)]).join("")}
  function shuffledQuestionIds(category=0,difficulty="all"){let bank=(window.JEGER_QUESTIONS||[]).filter(q=>(!category||q.c.includes(category))&&(difficulty==="all"||q.m===difficulty));if(bank.length<15)bank=(window.JEGER_QUESTIONS||[]).filter(q=>!category||q.c.includes(category));const ids=bank.map(q=>q.id);for(let i=ids.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[ids[i],ids[j]]=[ids[j],ids[i]]}return ids.slice(0,80)}
  async function createRoom(){
    try{await init();roomCode=makeCode();roomRef=rtdb.ref(`rooms/${roomCode}`);const p=me(),category=Number($("#mp-category")?.value||0),difficulty=$("#mp-difficulty")?.value||"all",payload={hostUid:uid,status:"lobby",createdAt:firebase.database.ServerValue.TIMESTAMP,expiresAt:now()+ROOM_LIFETIME,durationMs:ROUND_MS,settings:{category,difficulty},questionIds:shuffledQuestionIds(category,difficulty),players:{[uid]:{name:p.name,avatar:p.avatar||"gutt",joinedAt:firebase.database.ServerValue.TIMESTAMP,connected:true,lastSeen:firebase.database.ServerValue.TIMESTAMP,correct:0,wrong:0,earnedPoints:0,totalResponseMs:0,finished:false}}};await roomRef.set(payload);roomData=payload;localStorage.setItem(SESSION_KEY,roomCode);await markConnected();listen();showLobby()}catch(e){error("Kunne ikke lage rom: "+e.message)}
  }
  async function joinRoom(raw){
    const code=String(raw||"").toUpperCase().replace(/[^A-Z0-9]/g,"").slice(0,6);if(code.length!==6)return error("Romkoden skal ha 6 tegn.");
    try{await init();roomCode=code;roomRef=rtdb.ref(`rooms/${roomCode}`);const snap=await roomRef.once("value"),data=snap.val();if(!data)return error("Fant ikke rommet. Kontroller koden.");if(data.expiresAt&&data.expiresAt<now())return error("Dette spillerommet har utløpt.");if(!["lobby","countdown","playing"].includes(data.status))return error("Denne runden er avsluttet.");if(Object.keys(data.players||{}).length>=MAX_PLAYERS&&!data.players?.[uid])return error("Rommet er fullt (maks 12 spillere).");const p=me(),existing=data.players?.[uid],player=existing?{...existing,connected:true,lastSeen:firebase.database.ServerValue.TIMESTAMP}:{name:p.name,avatar:p.avatar||"gutt",joinedAt:firebase.database.ServerValue.TIMESTAMP,connected:true,lastSeen:firebase.database.ServerValue.TIMESTAMP,correct:0,wrong:0,earnedPoints:0,totalResponseMs:0,finished:false};await roomRef.child(`players/${uid}`).set(player);roomData={...data,players:{...(data.players||{}),[uid]:player}};localStorage.setItem(SESSION_KEY,roomCode);await markConnected();listen();if(data.status==="lobby")showLobby();else if(data.status==="countdown")runCountdown();else startRound()}catch(e){error("Kunne ikke bli med: "+e.message)}
  }
  function listen(){if(unsubscribe)unsubscribe();const cb=s=>onRoom(s.val());roomRef.on("value",cb);unsubscribe=()=>roomRef?.off("value",cb)}
  function onRoom(data){if(!data){error("Spillerommet er avsluttet.");return}const previous=roomData?.status;roomData=data;electHostIfNeeded();if(data.status==="lobby")renderPlayers();if(data.status==="countdown"&&previous!=="countdown")runCountdown();if(data.status==="playing"&&previous!=="playing")startRound();if(data.status==="finished"&&previous!=="finished")showResults();if(data.status==="playing"&&data.hostUid===uid){const players=Object.values(data.players||{}),allDone=players.length>0&&players.every(p=>p.finished);if(allDone)roomRef.child("status").set("finished")}}
  async function electHostIfNeeded(){if(!roomData||roomData.players?.[roomData.hostUid]?.connected!==false)return;const connected=Object.entries(roomData.players||{}).filter(([,p])=>p.connected!==false).map(([id])=>id).sort();if(!connected.length)return;const candidate=connected[0];if(candidate!==uid)return;await roomRef.child("hostUid").transaction(current=>current===roomData.hostUid?candidate:current)}
  function shareUrl(){const u=new URL(location.href);u.searchParams.set("challenge",roomCode);return u.toString()}
  function showLobby(){
    const host=roomData?.hostUid===uid;screen(panel(`<div class="mp-room">${roomCode}</div><div class="mp-lobby"><div><div class="mp-qr"><canvas id="mp-qr"></canvas></div><button class="mp-btn secondary" id="mp-share">Del lenke</button></div><div><h2>Spillere <span id="mp-count">1/${MAX_PLAYERS}</span></h2><div class="mp-players" id="mp-players"></div>${host?'<button class="mp-btn" id="mp-start" disabled>Start kampen</button>':'<p>Venter på at verten starter …</p>'}</div></div>`));bindClose();renderPlayers();
    if(globalThis.QRCode)QRCode.toCanvas($("#mp-qr"),shareUrl(),{width:190,margin:1,color:{dark:"#173521",light:"#ffffff"}}).catch(()=>{});
    $("#mp-share").onclick=async()=>{const data={title:"Jegerprøven – vennekamp",text:`Bli med i rom ${roomCode}`,url:shareUrl()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);$("#mp-share").textContent="Lenken er kopiert ✓"}}catch{}};
    if(host)$("#mp-start").onclick=startByHost;
  }
  function renderPlayers(){const box=$("#mp-players");if(!box||!roomData)return;const players=Object.entries(roomData.players||{});box.innerHTML=players.map(([id,p])=>`<div class="mp-player">${p.avatar==="jente"?"👧":"👦"} ${safe(p.name)} ${id===roomData.hostUid?"👑":""}</div>`).join("");if($("#mp-count"))$("#mp-count").textContent=`${players.length}/${MAX_PLAYERS}`;if($("#mp-start"))$("#mp-start").disabled=players.length<2}
  async function startByHost(){if(roomData.hostUid!==uid||Object.keys(roomData.players||{}).length<2)return;await roomRef.update({status:"countdown",startsAt:now()+COUNTDOWN_MS})}
  function runCountdown(){screen(panel(`<div style="display:grid;place-items:center;height:65vh"><div class="mp-countdown" id="mp-countdown">3</div></div>`,false));clearInterval(timer);timer=setInterval(()=>{const left=Math.max(0,Math.ceil((roomData.startsAt-now())/1000));if($("#mp-countdown"))$("#mp-countdown").textContent=left||"JAKT!";if(now()>=roomData.startsAt&&roomData.hostUid===uid)roomRef.child("status").set("playing")},100)}
  function startRound(){clearInterval(timer);const mine=roomData.players?.[uid];questionIndex=mine?.questionIndex||0;correct=mine?.correct||0;wrong=mine?.wrong||0;totalResponseMs=mine?.totalResponseMs||0;earnedPoints=mine?.earnedPoints||0;currentAttempts=0;finished=Boolean(mine?.finished);statsSaved=false;if(finished)return showWaitingResults();renderGame();timer=setInterval(tick,100)}
  function currentQuestion(){const id=roomData.questionIds?.[questionIndex],raw=(window.JEGER_QUESTIONS||[]).find(q=>String(q.id)===String(id));return raw&&window.JegerI18n?.question(raw,me().language||"nb")||raw}
  function tick(){const left=Math.max(0,(roomData.startsAt+ROUND_MS)-now());if($("#mp-time"))$("#mp-time").textContent=(left/1000).toFixed(1);if(left<=0)finishPlayer()}
  function renderGame(){const q=currentQuestion();if(!q)return finishPlayer();questionShownAt=performance.now();screen(panel(`<div class="mp-game"><aside class="mp-timer"><span>TID</span><strong id="mp-time">30.0</strong><div class="mp-mini-score">✅ <b>${correct}</b> &nbsp; ❌ <b>${wrong}</b><br>💰 <b>${earnedPoints}</b> patronpoeng</div></aside><article class="mp-question"><small>SPØRSMÅL ${questionIndex+1} • ${q.m==="22"?".22 LR":q.m==="12"?"KALIBER 12":"6,5×55"}</small><h2>${safe(q.q)}</h2>${q.image?`<img class="animal-photo" src="${safe(q.image)}" alt="Dyrebilde">`:""}<div class="mp-answers">${q.a.map((a,i)=>`<button data-mp-answer="${i}"><span>${String.fromCharCode(65+i)}</span>${safe(a)}</button>`).join("")}</div></article></div>`,false));document.querySelectorAll("[data-mp-answer]").forEach(b=>b.onclick=()=>answer(Number(b.dataset.mpAnswer),b))}
  function award(q){const p=me(),count=Math.max(1,3-currentAttempts),value=q.m==="22"?1:q.m==="12"?5:10,points=count*value;p.ammo=p.ammo||{22:0,12:0,65:0};p.ammo[q.m]=(p.ammo[q.m]||0)+count;p.score=(p.score||0)+points;earnedPoints+=points;if(typeof save==="function")save()}
  function answer(choice,button){if(finished)return;const q=currentQuestion();if(choice===q.r){award(q);correct++;totalResponseMs+=Math.round(performance.now()-questionShownAt);questionIndex++;currentAttempts=0;roomRef.child(`players/${uid}`).update({correct,wrong,earnedPoints,totalResponseMs,questionIndex});renderGame()}else{wrong++;currentAttempts++;button.classList.add("wrong");button.disabled=true;roomRef.child(`players/${uid}`).update({wrong,questionIndex})}}
  async function finishPlayer(){if(finished)return;finished=true;clearInterval(timer);await roomRef.child(`players/${uid}`).update({correct,wrong,earnedPoints,totalResponseMs,questionIndex,finished:true,finishedAt:firebase.database.ServerValue.TIMESTAMP});showWaitingResults();if(roomData.hostUid===uid)setTimeout(()=>roomRef?.child("status").set("finished"),3200)}
  function showWaitingResults(){screen(panel(`<div style="text-align:center;padding:35px"><h2>⏱️ Tiden er ute!</h2><p>Venter på resultatlisten …</p></div>`,false))}
  function saveStats(players){if(statsSaved)return;statsSaved=true;const p=me(),mine=roomData.players?.[uid]||{},rank=players.findIndex(x=>x.uid===uid)+1;p.mpStats=p.mpStats||{games:0,wins:0,bestCorrect:0,totalCorrect:0,totalWrong:0};p.mpStats.games++;if(rank===1)p.mpStats.wins++;p.mpStats.bestCorrect=Math.max(p.mpStats.bestCorrect,mine.correct||0);p.mpStats.totalCorrect+=(mine.correct||0);p.mpStats.totalWrong+=(mine.wrong||0);p.achievements=p.achievements||[];[["first_game",p.mpStats.games>=1],["first_win",p.mpStats.wins>=1],["ten_fast",(mine.correct||0)>=10],["perfect_round",(mine.correct||0)>=5&&(mine.wrong||0)===0]].forEach(([id,ok])=>{if(ok&&!p.achievements.includes(id))p.achievements.push(id)});if(typeof save==="function")save()}
  function showResults(){clearInterval(timer);const players=Object.entries(roomData.players||{}).map(([uid,p])=>({...p,uid})).sort((a,b)=>(b.correct||0)-(a.correct||0)||(a.wrong||0)-(b.wrong||0)||(a.totalResponseMs||0)-(b.totalResponseMs||0));saveStats(players);screen(panel(`<h2>🏆 Resultatliste</h2><table class="mp-results"><thead><tr><th>Plass</th><th>Spiller</th><th>Riktige</th><th>Feil</th><th>Patronpoeng</th><th>Svartid</th></tr></thead><tbody>${players.map((p,i)=>`<tr><td>${i+1}${i===0?" 🏆":""}</td><td>${safe(p.name)}</td><td>${p.correct||0}</td><td>${p.wrong||0}</td><td>${p.earnedPoints||0}</td><td>${((p.totalResponseMs||0)/1000).toFixed(1)} s</td></tr>`).join("")}</tbody></table><p>Kamper: ${me().mpStats?.games||0} · Seire: ${me().mpStats?.wins||0} · Personlig rekord: ${me().mpStats?.bestCorrect||0}</p><button class="mp-btn" data-mp-close>Tilbake til jaktbua</button>`,false));bindClose()}
  async function leave(){clearInterval(timer);if(unsubscribe){unsubscribe();unsubscribe=null}if(roomRef&&uid){try{await roomRef.child(`players/${uid}`).update({connected:false,lastSeen:firebase.database.ServerValue.TIMESTAMP});if(roomData?.status==="lobby"&&roomData.hostUid===uid){const others=Object.keys(roomData.players||{}).filter(id=>id!==uid);if(!others.length)await roomRef.remove()}}catch{}}localStorage.removeItem(SESSION_KEY);roomRef=null;roomData=null;roomCode="";document.getElementById("mp-root")?.remove();const u=new URL(location.href);u.searchParams.delete("challenge");history.replaceState({},"",u)}
  window.JegerMultiplayer={open};
  window.addEventListener("load",()=>{if(codeFromUrl()){const wait=setInterval(()=>{if(typeof profile==="function"&&profile()){clearInterval(wait);open()}},250);setTimeout(()=>clearInterval(wait),10000)}});
})();
