/* Tillegg 1: 100 permanente spørsmål. Regelverk kontrollert 01.09.2026. */
(()=>{
const A=[];
const q=(id,c,t,a,r,e,m="65",s="pensum")=>A.push({id,c,q:t,a,r,e,m,s,checked:"2026-09-01"});
/* 30: alder, jegerprøve og opplæringsjakt */
q("6.41",[6],"Ida fyller 14 år i november. Når kan hun tidligst ta jegerprøveeksamen?",["Fra 1. januar samme år","På 14-årsdagen","På 16-årsdagen"],0,"Jegerprøven kan tas fra kalenderåret du fyller 14 år.");
q("6.42",[6],"Hva betyr «kalenderåret du fyller 14 år»?",["Etter bursdagen","Hele året fra 1. januar","De første 14 ukene"],1,"Kalenderåret starter 1. januar.");
q("6.43",[6],"Ola fyller 14 år i desember. Kan aldersregelen åpne for opplæringsjakt på småvilt i september?",["Ja, når alle vilkår er oppfylt","Nei, aldri før bursdagen","Bare uten ledsager"],0,"Her gjelder kalenderåret.");
q("6.44",[6],"Må en opplæringsjeger under 16 ha bestått jegerprøven for småvilt?",["Ja","Nei","Bare for fugl"],1,"Jegerprøven kreves ikke ved denne opplæringsjakten.");
q("6.45",[6],"Hva må en ungdom ha fra foreldre eller foresatte før opplæringsjakt?",["Samtykke","Eget våpen","Eget terreng"],0,"Foreldre eller foresatte må samtykke.");
q("6.46",[6],"Hvor gammel må ledsageren minst være?",["18 år","20 år","25 år"],1,"Tilsynspersonen må ha fylt 20 år.");
q("6.47",[6],"Hvor lenge må ledsageren minst ha jaktet og betalt jegeravgift?",["Ett år","To år","Tre år"],2,"Kravet er minst tre år.");
q("6.48",[6],"Hvor nær må ledsageren være?",["Nær nok til å kontrollere og instruere","Tilgjengelig på telefon","Ledsageren kan være hjemme"],0,"Tilsynet må være reelt.");
q("6.49",[6],"Må ledsageren ha tillatelse fra rettighetshaveren?",["Ja","Nei","Bare ved storviltjakt"],0,"Ledsageren skal ha nødvendig tillatelse.");
q("6.50",[6],"Betaler en ungdom jegeravgift under lovlig opplæringsjakt?",["Ja","Nei, eleven er fritatt","Dobbel avgift"],1,"Opplæringsjegeren er fritatt.");
q("6.51",[6],"Når kan du tidligst jakte småvilt selvstendig etter aldersregelen?",["1. januar året du fyller 16","Når du faktisk har fylt 16","Når du fyller 14"],1,"Selvstendig småviltjakt krever fylte 16 år.");
q("6.52",[6],"En elev fyller 16 i oktober. Kan eleven jakte småvilt alene i september?",["Ja","Nei, eleven må vente til bursdagen","Ja, hvis eleven har hund"],1,"Her gjelder faktisk fødselsdag.");
q("6.53",[6],"Hva trenger en 16-åring normalt for selvstendig småviltjakt?",["Jegerprøve, jegeravgift og tillatelse","Bare ledsager","Bare legitimasjon"],0,"Alder alene er ikke nok.");
q("6.54",[6],"Når kan opplæringsjakt på storvilt tidligst begynne?",["Kalenderåret du fyller 16","På 18-årsdagen","Kalenderåret du fyller 14"],0,"Storviltsopplæring kan starte i kalenderåret du fyller 16.");
q("6.55",[6],"Sara fyller 16 i desember. Kan hun være opplæringsjeger på storvilt i september?",["Ja, dersom alle krav er oppfylt","Nei, aldri før bursdagen","Bare uten våpen"],0,"Kalenderårsregelen gjelder.");
q("6.56",[6],"Må jegerprøven være bestått før opplæringsjakt på storvilt?",["Ja","Nei","Bare på elg"],0,"Jegerprøven kreves.");
q("6.57",[6],"Hva må i tillegg være bestått ved opplæringsjakt på storvilt med rifle?",["Båtførerprøven","Storviltprøven","Fangstprøven"],1,"Skyteprøven for storviltjegere kreves.");
q("6.58",[6],"Kan en 17-åring delta i lisensfelling etter den vanlige regelen om opplæringsjakt?",["Ja","Nei","Bare uten ledsager"],1,"Opplæringsregelen gjelder ikke lisensfelling.");
q("6.59",[6],"Når kan du tidligst jakte storvilt selvstendig?",["Når du har fylt 18","1. januar året du fyller 18","Når du fyller 16"],0,"Storviltjakt krever fylte 18 år.");
q("6.60",[6],"Emil fyller 18 i november. Kan han jakte storvilt selvstendig i oktober?",["Ja","Nei","Bare med rifle"],1,"Han må ha fylt 18 år.");
q("6.61",[6],"Er bestått jegerprøve alene nok til å jakte selvstendig?",["Ja","Nei, flere krav må være oppfylt","Ja, med lånt våpen"],1,"Alder, avgift og tillatelser må også være i orden.");
q("6.62",[6],"Kan en 13-åring som fyller 14 neste år delta med våpen i opplæringsjakt?",["Ja","Nei","Bare med to ledsagere"],1,"Kalenderårsregelen har ikke begynt ennå.");
q("6.63",[6],"Hvem trenger ikke jegerprøve bare for å være med på jaktdagen?",["En observatør som ikke utøver jakt","En som jakter alene","En som setter feller alene"],0,"Å observere er ikke automatisk å utøve jakt.");
q("6.64",[6],"Utøver du automatisk jakt hvis du bare bærer mat for jaktlaget?",["Ja","Nei","Bare hvis sekken er grønn"],1,"Vanlig turfølge er ikke automatisk jaktutøvelse.");
q("6.65",[6],"Kan en uten jegerprøve skyte fordi en erfaren jeger står ved siden av?",["Ja, alltid","Bare ved lovlig opplæringsjakt","Ja, på korte hold"],1,"Alle vilkårene for opplæringsjakt må følges.");
q("6.66",[6],"Hva skiller ledsageren fra en vanlig jaktkamerat?",["Ledsageren har tilsynsansvar","Ingen forskjell","Ledsageren skal stå langt unna"],0,"Ledsageren skal kontrollere og instruere.");
q("6.67",[6],"Hvem må passe på at opplæringsreglene følges?",["Bare hunden","Eleven og ledsageren","Ingen på privat grunn"],1,"Begge må opptre ansvarlig.");
q("6.68",[6],"Når slutter ungdomsregelen for opplæringsjakt på småvilt?",["Når personen fyller 16","Ved nyttår samme år","Når personen fyller 18"],0,"Deretter gjelder ordinære regler.");
q("6.69",[6],"Når slutter ungdomsregelen for opplæringsjakt på storvilt?",["Når personen fyller 18","Ved nyttår samme år","Når personen fyller 20"],0,"Deretter gjelder ordinære regler.");
q("6.70",[6],"Hva er riktig huskeregel?",["Kalenderår kan åpne for opplæring, selvstendig jakt krever passert bursdag","All jakt starter 1. januar","Bursdagen betyr aldri noe"],0,"Reglene bruker kalenderår og fylte år forskjellig.");
/* 20: ny lov, termisk, drone og jaktfrie dager */
q("6.71",[6],"Hva er hovedregelen for termiske siktemidler under jakt?",["Alltid tillatt","Forbudt hvis ikke et unntak gjelder","Bare forbudt om sommeren"],1,"Viltressursloven har et hovedforbud.","65","regelverk");
q("6.72",[6],"Når kan termisk sikte brukes ved jakt på rødrev etter unntaket?",["I åpent terreng eller ved åteplass","Bare i tett skog","Alltid"],0,"Unntaket er avgrenset.","65","regelverk");
q("6.73",[6],"Når kan termisk sikte brukes ved jakt på villsvin etter unntaket?",["I åpent terreng eller ved åteplass","Bare fra båt","Aldri"],0,"Unntaket er avgrenset.","65","regelverk");
q("6.74",[6],"Kan termisk sikte brukes på hjort i alle kommuner?",["Ja","Nei, lokal forskrift må åpne for det","Ja, hvis utstyret er dyrt"],1,"Kommunen må ha åpnet for dette.","65","regelverk");
q("6.75",[6],"Hvor kan en lokal åpning for termisk hjortejakt gjelde?",["Åpent terreng","Inne i hus","Overalt"],0,"Unntaket avgrenses til åpent terreng.","65","regelverk");
q("6.76",[6],"Hva må gjøres etter lovlig felling av hjort med termisk sikte?",["Rapportere i Hjorteviltregisteret","Slette opplysningene","Bare si det til en venn"],0,"Bruken skal rapporteres.","65","regelverk");
q("6.77",[6,8],"Kan termisk sikte brukes ved ettersøk av påskutt hjortevilt?",["Ja, når reglene følges","Nei, aldri","Bare før skuddet"],0,"Forskriften har et ettersøksunntak.","65","regelverk");
q("6.78",[6,8],"Hvem varsles normalt før termisk brukes i slikt ettersøk?",["Grunneier, politi og kommune","Bare naboen","Ingen"],0,"Varslingskravene må følges.","65","regelverk");
q("6.79",[6],"Når trådte viltressursloven i kraft?",["1. juli 2026","1. januar 2020","31. mars 2028"],0,"Loven trådte i kraft 1. juli 2026.","65","regelverk");
q("6.80",[6],"Hva gjør du før termisk sikte brukes på hjort?",["Sjekker nasjonale og lokale regler","Spør bare butikken","Antar at det er lov"],0,"Reglene kan variere lokalt.","65","regelverk");
q("6.81",[6],"Når er jakt og fangst forbudt i juleperioden?",["24.–31. desember","Bare 25. desember","Hele januar"],0,"Forbudet gjelder fra og med 24. til og med 31. desember.","65","regelverk");
q("6.82",[6],"Kan du jakte 24. desember etter den generelle regelen?",["Nei","Ja før klokken 12","Ja på småvilt"],0,"24. desember er jaktfri.","65","regelverk");
q("6.83",[6],"Kan du jakte 31. desember etter den generelle regelen?",["Nei","Ja","Bare med hagle"],0,"31. desember er inkludert.","65","regelverk");
q("6.84",[6],"Hvilke påskedager er jaktfrie?",["Langfredag, påskeaften og første påskedag","Bare skjærtorsdag","Bare andre påskedag"],0,"Disse tre dagene er nevnt i loven.","65","regelverk");
q("6.85",[6],"Er alle søndager generelt jaktfrie?",["Ja","Nei","Bare i Nord-Norge"],1,"Det finnes ikke et generelt søndagsforbud.","65","regelverk");
q("6.86",[6],"Er 1. januar med i juleforbudet?",["Nei, men andre regler gjelder","Ja","Bare for hjort"],0,"Juleforbudet slutter 31. desember.","65","regelverk");
q("6.87",[6],"En art har jakttid 26. desember. Kan du jakte den dagen?",["Nei, juleforbudet gjelder","Ja","Bare alene"],0,"Det generelle forbudet gjelder uansett.","65","regelverk");
q("6.88",[6],"Kan lokale regler være strengere enn nasjonal jakttid?",["Ja","Nei","Bare for fugl"],0,"Lokale regler og jaktrett kan begrense jakten.","65","regelverk");
q("6.89",[6,8],"Kan drone brukes fritt til å lete etter friskt vilt under jakt?",["Nei","Ja","Bare med kamera"],0,"Droneunntaket gjelder bestemte ettersøk, ikke vanlig lokalisering.","65","regelverk");
q("6.90",[6,8],"Hva er viktig ved lovlig dronebruk i ettersøk?",["Følge vilkår og varsle rette instanser","Fly så høyt som mulig","Ikke fortelle noen"],0,"Jegeren må kunne vise at bruken er lovlig.","65","regelverk");
/* 25: artskunnskap og jakttider uten bilde */
q("5.41",[5],"Hvilket er minst av elg, hjort og rådyr?",["Rådyr","Hjort","Elg"],0,"Rådyret er minst.");
q("5.42",[5],"Hva kalles et rådyr under ett år?",["Kje","Kalv","Lam"],0,"Rådyrets unge kalles kje.");
q("5.43",[5],"Hva kalles hunnen hos rådyr?",["Geit","Kolle","Simle"],0,"Hunnen kalles geit.");
q("5.44",[5],"Hva kalles ungen hos elg og hjort?",["Kalv","Kje","Valp"],0,"Ungen kalles kalv.");
q("5.45",[5],"Hva kjennetegner vanligvis elgkua?",["Hun mangler gevir","Hun har størst gevir","Hun har stripet hale"],0,"Elgkua mangler normalt gevir.");
q("5.46",[5],"Hva er en spissbukk hos hjort?",["En ung hann med enkelt gevir","En voksen hunn","En kalv uten ører"],0,"Spissbukken er en ung hann.");
q("5.47",[5],"Hvilket hjortedyr har ofte lyst speil med tydelig mørk hale?",["Hjort","Rådyr","Elg"],0,"Dette er typisk for hjort.");
q("5.48",[5],"Hos hvilken art kan både hunner og hanner ha gevir?",["Villrein","Elg","Rådyr"],0,"Begge kjønn kan ha gevir hos villrein.");
q("5.49",[5,6],"Hva må du gjøre når kjønn eller alder har ulik jakttid?",["Bestemme riktig kategori før skudd","Skyte først","Bare se på størrelsen"],0,"Art, kjønn og alder må bestemmes sikkert.","65","regelverk");
q("5.50",[5,6],"Når starter den nasjonale jakttidsrammen for voksen rådyrbukk?",["10. august","25. september","1. november"],0,"Voksen bukk har en tidlig jaktstart.","65","regelverk");
q("5.51",[5,6],"Når starter den nasjonale jakttidsrammen for øvrig rådyrjakt?",["25. september","10. august","1. januar"],0,"Øvrig rådyrjakt starter senere.","65","regelverk");
q("5.52",[5,6],"Kan ei rådyrgeit felles under den tidlige bukkejakten?",["Nei","Ja","Bare alene"],0,"Den tidlige perioden gjelder voksen bukk.","65","regelverk");
q("5.53",[5,6],"Hvorfor må rådyrjegeren i august skille bukk fra geit?",["Bare voksen bukk har tidlig jaktstart","Geita er alltid større","Begge har alltid gevir"],0,"Kjønnet avgjør om jakttiden er åpen.","65","regelverk");
q("5.54",[5,6],"Er jakttiden alltid lik i hele landet for samme fugleart?",["Nei","Ja","Bare fjærfargen avgjør"],0,"Område, og noen ganger alder, kan gi forskjeller.","65","regelverk");
q("5.55",[5,6],"Hvilken storskarv kan jaktes i enkelte saltvannsområder i Sør-Norge?",["Ungfugl med hvit buk","Alle voksne","Alle hele året"],0,"Forskriften avgrenser jakten til ungfugl der.","65","regelverk");
q("5.56",[5,6],"Hva gjelder for kortnebbgås i Finnmark?",["Arten er fredet der","Jakt hele året","Bare voksne er fredet"],0,"Kortnebbgås er fredet i Finnmark.","65","regelverk");
q("5.57",[5],"Hvordan skiller ung storskarv seg ofte fra voksen?",["Ungfuglen har lys eller hvit buk","Ungfuglen har gevir","Ungfuglen mangler vinger"],0,"Lys buk er et viktig alderskjennetegn.");
q("5.58",[5],"Hva kjennetegner ei røy?",["Brunspettet og mindre enn tiuren","Svart med lyrehale","Grønt hode"],0,"Røya er hunnen hos storfugl.");
q("5.59",[5],"Hva kjennetegner ei orrhøne?",["Brunspettet fjærdrakt","Svart drakt og lyrehale","Hvit halsring"],0,"Orrhøna er brunspettet.");
q("5.60",[5],"Hvilken fugl er størst?",["Tiur","Orrhane","De er like store"],0,"Tiuren er betydelig større.");
q("5.61",[5],"Hva hjelper med å skille lirype og fjellrype?",["Leveområde og drakt","Fjellrypa kan ikke fly","Lirypa lever bare ved sjøen"],0,"Både miljø og kjennetegn må vurderes.");
q("5.62",[5],"Hvilken rype har ofte mørk stripe gjennom øyet?",["Lirype","Fjellrype","Ingen av dem"],0,"Lirypa har ofte tydelig øyestripe.");
q("5.63",[5],"Hvordan flyr rugda ofte når den støkkes?",["Raskt og sikksakkpreget","Den løper alltid","Den svever som en ørn"],0,"Rugda kan fly uregelmessig.");
q("5.64",[5],"Hva er viktig før skudd mot en and i høstdrakt?",["Sikker artsbestemmelse","Velge den største","Se på vannfargen"],0,"Flere ender kan ligne i høstdrakt.");
q("5.65",[5],"Hva kjennetegner ofte kvinandhannen?",["Mørkt hode med hvit kinnflekk","Stort gevir","Helt grønn kropp"],0,"Den hvite kinnflekken er typisk.");
/* 15: jakthunder og uttrykk */
q("7.41",[7],"Hva betyr «løs på drevet halsende hund»?",["Hunden følger viltet løs og gir lyd","Hunden går stille i line","Hunden sitter på post"],0,"Halsingen forteller at hunden driver vilt.");
q("7.42",[7],"Hva betyr det at en hund gir hals?",["Den bruker stemmen under arbeidet","Den legger seg","Den drikker"],0,"Å gi hals betyr å bjeffe eller lose.");
q("7.43",[7],"Hva er fotarbeid før en los?",["Hunden arbeider med sporet","Hunden venter i bilen","Jegeren skyter"],0,"Fotarbeidet skjer før viltet reiser.");
q("7.44",[7],"Hva betyr uttak under jakt med drivende hund?",["Viltet reiser og losen begynner","Hunden tas ut av bilen","Våpenet tømmes"],0,"Uttaket starter drevet.");
q("7.45",[7],"Hva er en stålos?",["Hunden gir hals mot vilt som står","Hunden løper stille","Jegeren roper"],0,"Stålos kan oppstå når en hund stiller elg.");
q("7.46",[7],"Hva er en drevlos?",["Hunden gir hals etter vilt i bevegelse","Hunden sover","Jegeren lokker"],0,"Drevlosen følger viltet.");
q("7.47",[7],"Hvordan arbeider en bandhund på elgjakt?",["Kontrollert i line med føreren","Løs over lange avstander","Ved å apportere"],0,"Bandhunden arbeider i line.");
q("7.48",[7],"Hvordan arbeider en løshund på elgjakt?",["Søker løs og prøver å stille elgen","Alltid i kort line","Sitter ved sekken"],0,"Løshunden arbeider løs.");
q("7.49",[7],"Hva betyr apport?",["Finne og bringe felt vilt","Drive elg","Grave felle"],0,"Apportøren henter vilt.");
q("7.50",[7],"Hva betyr stand hos fuglehund?",["Hunden stanser og markerer fugl","Hunden loser hare","Hunden legger seg i bilen"],0,"Hunden stanser og peker med kropp og hode mot fuglen. Jegeren går rolig fram og gjør seg klar før fuglen eventuelt reises. Det skytes først når arten er sikkert bestemt, fuglen er lovlig å jakte, skuddholdet er forsvarlig og retningen er trygg for mennesker og hund.");
q("7.51",[7],"Hva skiller ofte støtende fra drivende hund?",["Den støtende arbeider kortere nær føreren","Ingen forskjell","Den drivende brukes bare i vann"],0,"Arbeidsmåte og avstand er ulike.");
q("7.52",[7],"Hvorfor bør jegeren kjenne hundens losmål?",["For å tolke hundens arbeid","For å velge farge","For å veie sekken"],0,"Stemmen kan gi nyttig informasjon.");
q("7.53",[7],"Kan hunde-GPS erstatte innkalling og kontroll?",["Nei","Ja, alltid","Bare med fullt batteri"],0,"GPS er bare et hjelpemiddel.");
q("7.54",[7],"Hva gjør du når hunden nærmer seg en trafikkert vei?",["Prøver å få kontroll","Lar den fortsette","Skyter mot veien"],0,"Trafikk krever rask og sikker handling.");
q("7.55",[7],"Hvorfor trenger jakthunden pauser og vann?",["For helse og velferd","For at jakten skal vare lengst","Fordi GPS-en krever det"],0,"Jegeren har ansvar for hunden.");
/* 10: andre pensumhull */
q("2.41",[2,6],"Hvem skal hindre at uvedkommende får tilgang til jaktvåpen?",["Våpeneieren eller ansvarlig bruker","Butikken","Ingen"],0,"Våpen må sikres forsvarlig.");
q("2.42",[2,3],"Kan et ladd jaktvåpen ligge løst i bilen?",["Nei","Ja, i låst bil","Ja, på korte turer"],0,"Våpen transporteres forsvarlig og uladd.");
q("2.43",[2],"Hva gjør du hvis et våpen blir stjålet?",["Varsler politiet raskt","Venter til neste år","Kjøper nytt"],0,"Tyveri skal meldes.");
q("3.41",[3],"Hvorfor kan frossen mark være farlig kulebakgrunn?",["Kulen kan rikosjettere","Kulen fryser","Våpenet blir lydløst"],0,"Hard mark kan gi rikosjett.");
q("3.42",[3],"Er en bakketopp sikkert kulefang når du ikke ser bak?",["Nei","Ja","Bare for små kalibre"],0,"Kulen kan fortsette over toppen.");
q("4.41",[4],"Hvor bør blikket være ved hagleskyting mot leirdue?",["På målet","Bare på kornet","På bakken"],0,"Blikket følger målet.");
q("4.42",[4],"Hvorfor fortsetter hagla å svinge idet skuddet går?",["For å beholde riktig foranhold","For mindre lyd","For større hagl"],0,"Gjennomsving hindrer at du stopper bak målet.");
q("8.41",[8],"Hva gjør du selv om du tror skuddet var bom?",["Kontrollerer skuddstedet","Jakter straks videre","Drar hjem"],0,"Jegeren må forsikre seg om utfallet.");
q("9.41",[9],"Hvorfor kjøles felt vilt raskt og kontrollert?",["For hygiene og kjøttkvalitet","For å gjøre det vått","For å slippe rengjøring"],0,"Nedkjøling begrenser bakterievekst.");
q("9.42",[9],"Hva gjør du hvis organene viser tydelige tegn på sykdom?",["Stanser og søker faglig vurdering","Spiser dem først","Skjuler funnet"],0,"Unormale funn skal tas alvorlig.");
window.JEGER_QUESTIONS.push(...A);
})();
