/* Outfitter Shop. ID-er og priser er permanente når varen er tatt i bruk. */
window.OUTFITTER_ITEMS=[
  {id:'caps-oransje',name:'Oransje jaktcaps',icon:'cap',color:'#ff6a00',price:40,tier:'Start',type:'Hodeplagg'},
  {id:'lue-rosa',name:'Rosa jaktlue',icon:'beanie',color:'#ff69b4',price:55,tier:'Start',type:'Hodeplagg'},
  {id:'caps-lilla',name:'Lilla jaktcaps',icon:'cap',color:'#7d3cff',price:65,tier:'Start',type:'Hodeplagg'},
  {id:'jd-freja-fleece',name:'Jaktdamer fleeceanorakk',icon:'camo-suit',price:180,tier:'Bronse',type:'Overdel',wearSlot:'torso',fits:['jente','dame'],source:'Jaktdamer.no',sourceUrl:'https://www.jaktdamer.no/products/freja-fleccejakke',image:'assets/jaktdamer/freja-fleeceanorakk.jpg',thumb:'assets/jaktdamer/thumbs/freja-fleeceanorakk.jpg',description:'Myk og stille fleeceanorakk i brune toner.'},
  {id:'jd-lappmark-bukse',name:'Jaktdamer friluftsbukse',icon:'camo-suit',price:240,tier:'Bronse',type:'Bukse',wearSlot:'legs',fits:['jente','dame'],source:'Jaktdamer.no',sourceUrl:'https://www.jaktdamer.no/products/lappmark-ultra-friluftsbokse',image:'assets/jaktdamer/lappmark-ultra-bukse.jpg',thumb:'assets/jaktdamer/thumbs/lappmark-ultra-bukse.jpg',description:'Stille friluftsbukse med stretch og forsterkede knær.'},
  {id:'jd-artemis-softshell',name:'Jaktdamer softshell-jaktjakke',icon:'camo-suit',price:320,tier:'Sølv',type:'Overdel',wearSlot:'torso',fits:['jente','dame'],source:'Jaktdamer.no',sourceUrl:'https://www.jaktdamer.no/products/artemis-softshell-jaktjakke',image:'assets/jaktdamer/artemis-softshell-jaktjakke.jpg',thumb:'assets/jaktdamer/thumbs/artemis-softshell-jaktjakke.jpg',description:'Fôret softshelljakke med mørkt jaktmønster og rosa detaljer.'},
  {id:'jd-rikvi-fleece',name:'Jaktdamer jaktfleece',icon:'camo-suit',price:420,tier:'Sølv',type:'Overdel',wearSlot:'torso',fits:['jente','dame'],source:'Jaktdamer.no',sourceUrl:'https://www.jaktdamer.no/products/rikvi-jaktfleece',image:'assets/jaktdamer/rikvi-jaktfleece.jpg',thumb:'assets/jaktdamer/thumbs/rikvi-jaktfleece.jpg',description:'Varm og svært stille jaktfleece med stor frontlomme.'},
  {id:'jd-alva-ildri',name:'Jaktdamer jaktanorakk',icon:'camo-suit',price:650,tier:'Gull',type:'Overdel',wearSlot:'torso',fits:['jente','dame'],source:'Jaktdamer.no',sourceUrl:'https://www.jaktdamer.no/products/anorakk-alva-ildri',image:'assets/jaktdamer/alva-ildri-anorakk.jpg',thumb:'assets/jaktdamer/thumbs/alva-ildri-anorakk.jpg',description:'Vind- og vanntett jaktanorakk i brun og grønn farge.'},
  {id:'jd-dog-sports-plomme',name:'Jaktdamer jakke – plomme',icon:'camo-suit',price:800,tier:'Gull',type:'Overdel',wearSlot:'torso',fits:['jente','dame'],source:'Jaktdamer.no',sourceUrl:'https://www.jaktdamer.no/products/dog-sports-jakke-20',image:'assets/jaktdamer/dog-sports-jakke-plomme.jpg',thumb:'assets/jaktdamer/thumbs/dog-sports-jakke-plomme.jpg',description:'Vind- og vanntett jakke i plommefarge med mange praktiske lommer.'},
  {id:'floyte-rev',name:'Revefløyte',icon:'call-fox',price:80,tier:'Start',type:'Lokkeutstyr'},
  {id:'floyte-radyr',name:'Rådyrlokk med gummiblære',icon:'call-roe',price:100,tier:'Start',type:'Lokkeutstyr'},
  {id:'sekk-12',name:'Dagstursekk 12 L',icon:'backpack',price:120,tier:'Start',type:'Sekk'},
  {id:'kamo-skog',name:'Skogskamo jaktsett',icon:'camo-suit',color:'#496a32',price:160,tier:'Bronse',type:'Klær'},
  {id:'kamo-fjell',name:'Fjellkamo jaktsett',icon:'camo-suit',color:'#8b8a78',price:190,tier:'Bronse',type:'Klær'},
  {id:'lokkefugl-and',name:'Lokkefugl – stokkand',icon:'decoy-duck',price:220,tier:'Bronse',type:'Lokkeutstyr'},
  {id:'bulvan-gas',name:'Lokkefugl – gås',icon:'decoy-goose',price:260,tier:'Bronse',type:'Lokkeutstyr'},
  {id:'andefloyte',name:'Lokkefløyte – stokkand',icon:'call-duck',price:290,tier:'Bronse',type:'Lokkeutstyr'},
  {id:'gasefloyte',name:'Lokkefløyte – gås',icon:'call-goose',price:340,tier:'Sølv',type:'Lokkeutstyr'},
  {id:'hubro-bulvan',name:'Hubrobulvan',icon:'decoy-owl',price:360,tier:'Sølv',type:'Lokkeutstyr'},
  {id:'sekk-30',name:'Jaktsekk 30 L',icon:'backpack',price:300,tier:'Sølv',type:'Sekk'},
  {id:'kikkert-8x42',name:'Håndkikkert 8×42',icon:'binoculars',price:380,tier:'Sølv',type:'Optikk'},
  {id:'jaktradio',name:'Jaktradio',icon:'radio',price:450,tier:'Sølv',type:'Elektronikk'},
  {id:'borsestokk-oransje',name:'Oransje børsestokk',icon:'stock',color:'#e87522',price:520,tier:'Sølv',type:'Våpenstil'},
  {id:'kikkertsikte-1',name:'Kikkertsikte 1–6×',icon:'scope',price:650,tier:'Gull',type:'Optikk'},
  {id:'sekk-45',name:'Jaktsekk 45 L',icon:'backpack',price:750,tier:'Gull',type:'Sekk'},
  {id:'hund-gps',name:'GPS til Jerven',icon:'dog-gps',price:900,tier:'Gull',type:'Hund'},
  {id:'jeger-gps',name:'Håndholdt jeger-GPS',icon:'gps',price:1100,tier:'Gull',type:'Elektronikk'},
  {id:'kikkertsikte-2',name:'Kikkertsikte 3–12×',icon:'scope',price:1350,tier:'Platina',type:'Optikk'},
  {id:'jakttarn',name:'Jakttårn i tre',icon:'tower',price:1700,tier:'Platina',type:'Leirplass'},
  {id:'jerven-premie',name:'Jerven – jaktkameratmerke',icon:'paw',price:2100,tier:'Platina',type:'Hund'},
  {id:'jaktbu',name:'Jaktbu',icon:'cabin',price:2800,tier:'Mester',type:'Leirplass'},
  {id:'termisk-hand',name:'Termisk håndkikkert',icon:'thermal',price:3800,tier:'Mester',type:'Optikk'},
  {id:'mesterpakke',name:'Jervens mesterutstyr',icon:'trophy',price:5000,tier:'Legende',type:'Samling'}
];
